---
- name: make a hacklab
  hosts: all

  roles:
   - debian-common-base
   - role: debian-backports
     pin_backports: 700
   - debian-journald
   - debian-networkd
   - role: debian-influxdata
     influx_install: ["telegraf"]

   - role: hacklab
     net_dev: enp0s25
     hostname: polymorph

