---
- name: disable apt translations
  copy: src=99translations dest=/etc/apt/apt.conf.d/ owner=root group=root mode=0644

- name: apt, don't install recommended and suggested packages
  copy: src=99apt-no-install dest=/etc/apt/apt.conf.d/ owner=root group=root mode=0644

- name: make sure apt cache is up to date
  apt: update_cache=yes cache_valid_time=86400

- name: download and install latest updates
  apt: upgrade=dist

- name: install must-have tools
  apt: pkg={{ item }} state=installed
  with_items:
    - apt-transport-https
    - locales
    - sysstat
    - rsync
    - vim
    - strace
    - tcpdump
    - lsof
    - traceroute
    - tmux
    - python-pycurl
    - unzip
    - logrotate
    - less
    - curl
    - libnss-systemd
    - libnss-resolve
    - libnss-myhostname
    - systemd-cron

- name: remove unneeded stuff
  apt: pkg={{ item }} state=absent
  with_items:
    - whoopsie
    - apport
    - popularity-contest
    - update-notifier-common


- name: set timezone to GMT
  debconf: name=tzdata question=tzdata/Areas vtype=select value=Etc/GMT0

- name: create en_US.UTF-8 locale
  locale_gen: name=en_US.UTF-8 state=present
