---
- name: add grafana repo key
  apt_key: id=C2E73424D59097AB url=https://packagecloud.io/gpg.key

- name: add grafana repo
  apt_repository: state=present repo='deb https://packagecloud.io/grafana/stable/debian/ {{ ansible_distribution_release }} main'

- name: install grafana
  apt: name=grafana state=latest
